#!/bin/bash
path="${@: -1}"
dir=$(dirname "$path")

hash=$(git -C "$dir" log \
	   --format="%ad %H" \
	   --date=format:"%s" \
	   --grep="\[date skip\]" \
	   --invert-grep \
	   -- $(basename "$path") |\
	   sort -r |\
	   awk '{ print $2 }' |\
	   head -n1)

git -C "$dir" show --format="%ad" --quiet "${@:1:$#-1}" "${hash}"
